spring:
  application:
    name: CurrencyConverter

  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}
  datasource:
    url: jdbc:mysql://localhost:3306/currency_collector_db?serverTimezone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbitmq

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

scheduling:
  cron: "0 */10 * * * *"

fixer:
  url: ${FIXER_URL}
  key: ${FIXER_KEY}

external:
  service1:
    url: http://localhost:8081/api/v1
  service2:
    url: http://localhost:8082/api/v2

