spring:
  application:
    name: CurrencyGateway

  security:
    user:
      name: "admin"
      password: "password"
  datasource:
    url: jdbc:mysql://localhost:3306/currency_collector_db?serverTimezone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration


  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbitmq

logging:
  level:
    com.mihail.currencyconverter:
      DEBUG

scheduling:
  cron: "0 */10 * * * *"